title: AnamnesiA
description: "Un gioco di ruolo di horror psicologico"
permalink: pretty
remote_theme: just-the-docs/just-the-docs
color_scheme: anamnesia
encoding: UTF-8

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

include:
  - js

# Back to top link
back_to_top: true
back_to_top_text: "Torna su"

footer_content: "Game Design e Testi: Riccardo Cangini &bull; <a href=\"https://creativecommons.org/licenses/by-sa/4.0\">CC-BY-SA 4.0</a>"

last_edit_timestamp: true
last_edit_time_format: "%e %b %Y alle %H:%M"

# Aux links (top right)
aux_links:
  "Scarica PDF":
    - "https://github.com/TUOUSERNAME/anamnesia/releases/latest/download/anamnesia-quickstart.pdf"
  "Kickstarter":
    - "#"

aux_links_new_tab: true
